ProductManagementSystem/Pages/GroupPriceFilters/Create.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;
using Catalog.Data.Core.Models;
using Catalog.Data.Persistence;

namespace ProductManagementSystem.Pages.GroupPriceFilters
{
    public class CreateModel : PageModel
    {
        private readonly Catalog.Data.Persistence.CatalogDatabaseContext _context;

        public CreateModel(Catalog.Data.Persistence.CatalogDatabaseContext context)
        {
            _context = context;
        }

        public IActionResult OnGet()
        {
        ViewData["GroupId"] = new SelectList(_context.Groups, "Id", "Name");
        ViewData["PriceFilterId"] = new SelectList(_context.PriceFilters, "Id", "Id");
            return Page();
        }

        [BindProperty]
        public GroupPriceFilter GroupPriceFilter { get; set; }

        public async Task<IActionResult> OnPostAsync()
        {
            if (!ModelState.IsValid)
            {
                return Page();
            }

            _context.GroupPriceFilters.Add(GroupPriceFilter);
            await _context.SaveChangesAsync();

            return RedirectToPage("./Index");
        }
    }
}

ProductManagementSystem/Pages/GroupPriceFilters/Delete.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using Catalog.Data.Core.Models;
using Catalog.Data.Persistence;

namespace ProductManagementSystem.Pages.GroupPriceFilters
{
    public class DeleteModel : PageModel
    {
        private readonly Catalog.Data.Persistence.CatalogDatabaseContext _context;

        public DeleteModel(Catalog.Data.Persistence.CatalogDatabaseContext context)
        {
            _context = context;
        }

        [BindProperty]
        public GroupPriceFilter GroupPriceFilter { get; set; }

        public async Task<IActionResult> OnGetAsync(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            GroupPriceFilter = await _context.GroupPriceFilters
                .Include(g => g.Group)
                .Include(g => g.PriceFilter).SingleOrDefaultAsync(m => m.GroupId == id);

            if (GroupPriceFilter == null)
            {
                return NotFound();
            }
            return Page();
        }

        public async Task<IActionResult> OnPostAsync(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            GroupPriceFilter = await _context.GroupPriceFilters.FindAsync(id);

            if (GroupPriceFilter != null)
            {
                _context.GroupPriceFilters.Remove(GroupPriceFilter);
                await _context.SaveChangesAsync();
            }

            return RedirectToPage("./Index");
        }
    }
}

ProductManagementSystem/Pages/GroupPriceFilters/Details.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using Catalog.Data.Core.Models;
using Catalog.Data.Persistence;

namespace ProductManagementSystem.Pages.GroupPriceFilters
{
    public class DetailsModel : PageModel
    {
        private readonly Catalog.Data.Persistence.CatalogDatabaseContext _context;

        public DetailsModel(Catalog.Data.Persistence.CatalogDatabaseContext context)
        {
            _context = context;
        }

        public GroupPriceFilter GroupPriceFilter { get; set; }

        public async Task<IActionResult> OnGetAsync(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            GroupPriceFilter = await _context.GroupPriceFilters
                .Include(g => g.Group)
                .Include(g => g.PriceFilter).SingleOrDefaultAsync(m => m.GroupId == id);

            if (GroupPriceFilter == null)
            {
                return NotFound();
            }
            return Page();
        }
    }
}

ProductManagementSystem/Pages/GroupPriceFilters/Edit.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Catalog.Data.Core.Models;
using Catalog.Data.Persistence;

namespace ProductManagementSystem.Pages.GroupPriceFilters
{
    public class EditModel : PageModel
    {
        private readonly Catalog.Data.Persistence.CatalogDatabaseContext _context;

        public EditModel(Catalog.Data.Persistence.CatalogDatabaseContext context)
        {
            _context = context;
        }

        [BindProperty]
        public GroupPriceFilter GroupPriceFilter { get; set; }

        public async Task<IActionResult> OnGetAsync(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            GroupPriceFilter = await _context.GroupPriceFilters
                .Include(g => g.Group)
                .Include(g => g.PriceFilter).SingleOrDefaultAsync(m => m.GroupId == id);

            if (GroupPriceFilter == null)
            {
                return NotFound();
            }
           ViewData["GroupId"] = new SelectList(_context.Groups, "Id", "Name");
           ViewData["PriceFilterId"] = new SelectList(_context.PriceFilters, "Id", "Id");
            return Page();
        }

        public async Task<IActionResult> OnPostAsync()
        {
            if (!ModelState.IsValid)
            {
                return Page();
            }

            _context.Attach(GroupPriceFilter).State = EntityState.Modified;

            try
            {
                await _context.SaveChangesAsync();
            }
            catch (DbUpdateConcurrencyException)
            {
                if (!GroupPriceFilterExists(GroupPriceFilter.GroupId))
                {
                    return NotFound();
                }
                else
                {
                    throw;
                }
            }

            return RedirectToPage("./Index");
        }

        private bool GroupPriceFilterExists(int id)
        {
            return _context.GroupPriceFilters.Any(e => e.GroupId == id);
        }
    }
}

ProductManagementSystem/Pages/Groups/Create.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;
using Catalog.Data.Core.Models;
using Catalog.Data.Persistence;

namespace ProductManagementSystem
{
    public class CreateModel : PageModel
    {
        private readonly Catalog.Data.Persistence.CatalogDatabaseContext _context;

        public CreateModel(Catalog.Data.Persistence.CatalogDatabaseContext context)
        {
            _context = context;
        }

        public IActionResult OnGet()
        {
        ViewData["ParentId"] = new SelectList(_context.Groups, "Id", "Name");
            return Page();
        }

        [BindProperty]
        public Group Group { get; set; }

        public async Task<IActionResult> OnPostAsync()
        {
            if (!ModelState.IsValid)
            {
                return Page();
            }

            var emptyGroup = new Group();

            if (await TryUpdateModelAsync<Group>(
                emptyGroup,
                "group",
                g => g.Name,
                g => g.ParentId,
                g => g.Description))
            {
                Group.DateCreated = DateTime.UtcNow;
                Group.DateCreatedByUserId = 1; //TODO Change hardcoding to actual user id
                Group.DateLastModified = DateTime.UtcNow;
                Group.DateLastModifiedByUserId = 1; //TODO Change hardcoding to actual user id

                _context.Groups.Add(Group);
                await _context.SaveChangesAsync();

                return RedirectToPage("./Index");
            }

            return null;
        }
    }
}

ProductManagementSystem/Pages/Price/Import.cshtml.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Catalog.Data.Core.Models;
using Catalog.Data.Persistence;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using NPOI.HSSF.UserModel;
using NPOI.SS.UserModel;
using NPOI.XSSF.UserModel;

namespace ProductManagementSystem.Pages.Price
{
    public class ImportModel : PageModel
    {
        private IHostingEnvironment _hostingEnvironment;
        private readonly CatalogDatabaseContext _context;
        private readonly UnitOfWork _unitOfWork;

        public ImportModel(CatalogDatabaseContext context, IHostingEnvironment hostingEnvironment)
        {
            _hostingEnvironment = hostingEnvironment;
            _context = context;
            _unitOfWork = new UnitOfWork(_context);
        }

        public void OnGet()
        {
        }

        public ActionResult OnPostImport()
        {
            IFormFile file = Request.Form.Files[0];
            string folderName = "Upload";
            string webRootPath = _hostingEnvironment.WebRootPath;
            string newPath = Path.Combine(webRootPath, folderName);
            StringBuilder sb = new StringBuilder();

            if (!Directory.Exists(newPath))
            {
                Directory.CreateDirectory(newPath);
            }

            if (file.Length > 0)
            {
                string sFileExtension = Path.GetExtension(file.FileName).ToLower();
                ISheet sheet;
                string fullPath = Path.Combine(newPath, file.FileName);
                var products = new List<GroupTirePrice>();

                using (var stream = new FileStream(fullPath, FileMode.Create))
                {
                    file.CopyTo(stream);
                    stream.Position = 0;

                    if (sFileExtension == ".xls")
                    {
                        HSSFWorkbook hssfwb = new HSSFWorkbook(stream); //This will read the Excel 97-2000 formats

                        sheet = hssfwb.GetSheetAt(0); //get first sheet from workbook
                    }
                    else
                    {
                        XSSFWorkbook hssfwb = new XSSFWorkbook(stream); //This will read 2007 Excel format

                        sheet = hssfwb.GetSheetAt(0); //get first sheet from workbook
                    }

                    IRow headerRow = sheet.GetRow(0); //Get Header Row
                    int cellCount = headerRow.LastCellNum;

                    sb.Append("<table class='table'><tr>");

                    for (int j = 0; j < cellCount; j++)
                    {
                        NPOI.SS.UserModel.ICell cell = headerRow.GetCell(j);

                        if (cell == null || string.IsNullOrWhiteSpace(cell.ToString())) continue;

                        sb.Append("<th>" + cell.ToString() + "</th>");

                        //Validate proper headers
                        string[] validHeaders =
                        {
                            "partnumber",
                            "manufacturerpartnumber",
                            "price"
                        };

                        if (!Array.Exists(validHeaders, element => element == cell.ToString()))
                        {
                            //Error unknown header
                        }
                    }

                    sb.Append("</tr>");

                    sb.AppendLine("<tr>");

                    for (int i = (sheet.FirstRowNum + 1); i <= sheet.LastRowNum; i++) //Read Excel File
                    {
                        IRow row = sheet.GetRow(i);
                        var price = new GroupTirePrice();

                        if (row == null) continue;

                        if (row.Cells.All(d => d.CellType == CellType.Blank)) continue;

                        for (int j = row.FirstCellNum; j < cellCount; j++)
                        {
                            if (row.GetCell(j) != null)
                            {
                                sb.Append("<td>" + row.GetCell(j).ToString() + "</td>");
                            }

                            var header = headerRow.GetCell(j).StringCellValue;

                            switch (header)
                            {
                                case "ourpartnum":
                                    break;

                                case "manufacturerpartnum":
                                    var tire = _unitOfWork.Tires.Find(x => x.ManufacturerPartNumber == row.GetCell(j).ToString()).SingleOrDefault();
                                    var group = _unitOfWork.Groups.Get(1);

                                    var priceFilter = new PriceFilter();

                                    priceFilter.IsActive = true;
                                    priceFilter.Name = tire.Name.ToString();
                                    priceFilter.UserId = 1;
                                    priceFilter.PriceType = PriceTypes.Default;
                                    //Find maximum order for existing prices for group tire price

                                    if (tire != null)
                                    {
                                        var selection = new SelectionCriteria();
                                        selection.Source = "Product";
                                        selection.Name = "IdentificationNumber";
                                        selection.Value = tire.IdentificationNumber.ToString();
                                        selection.PriceFilter = priceFilter;
                                    }
                                    break;

                                case "price":
                                    break;

                                default:
                                    break;
                            }
                            //Validate data
                            //Add data
                        }
                        products.Add(price);

                        sb.AppendLine("</tr>");
                    }
                    _unitOfWork.GroupTirePrices.AddRange(products);
                    _unitOfWork.Complete();
                    sb.Append("</table>");
                }
            }

            return this.Content(sb.ToString());
        }

        public async Task<IActionResult> OnPostExport()
        {
            string sWebRootFolder = _hostingEnvironment.WebRootPath;
            string sFileName = "Price_List_" + DateTime.Today.Year.ToString() + DateTime.Today.Month.ToString() + DateTime.Today.Day.ToString() + ".xlsx";
            string URL = string.Format("{0}://{1}/{2}", Request.Scheme, Request.Host, sFileName);
            FileInfo file = new FileInfo(Path.Combine(sWebRootFolder, sFileName));
            var memory = new MemoryStream();

            using (var fs = new FileStream(Path.Combine(sWebRootFolder, sFileName), FileMode.Create, FileAccess.Write))
            {
                IWorkbook workbook;

                workbook = new XSSFWorkbook();

                ISheet excelSheet = workbook.CreateSheet("Point S Price");

                var prices = _unitOfWork.GroupProductPrices;

                var rowNumber = 0;
                IRow row = excelSheet.CreateRow(rowNumber);
                row.CreateCell(0).SetCellValue("Group");
                row.CreateCell(1).SetCellValue("Manufacturer Number");
                row.CreateCell(2).SetCellValue("Product Name");
                row.CreateCell(3).SetCellValue("Price");

                foreach (var price in prices.GetAllWIthProducts())
                {
                    rowNumber += 1;

                    row = excelSheet.CreateRow(rowNumber);
                    row.CreateCell(0).SetCellValue(price.Group.ToString());
                    row.CreateCell(1).SetCellValue(price.Product.ToString());
                    row.CreateCell(2).SetCellValue(_unitOfWork.Tires.Get(price.Product.Id).ManufacturerPartNumber.ToString());
                    row.CreateCell(3).SetCellValue(price.Price.ToString());
                }

                workbook.Write(fs);
            }

            using (var stream = new FileStream(Path.Combine(sWebRootFolder, sFileName), FileMode.Open))
            {
                await stream.CopyToAsync(memory);
            }

            memory.Position = 0;

            return File(memory, "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet", sFileName);
        }
    }
}

ProductManagementSystem/Pages/Price/Create.cshtml
@page
@model ProductManagementSystem.Pages.Price.CreateModel

@{
    ViewData["Title"] = "Create";
}

<h2>Create</h2>

<h4>GroupTirePrice</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form method="post">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="GroupTirePrice.Price" class="control-label"></label>
                <input asp-for="GroupTirePrice.Price" class="form-control" />
                <span asp-validation-for="GroupTirePrice.Price" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="GroupTirePrice.StartDate" class="control-label"></label>
                <input asp-for="GroupTirePrice.StartDate" class="form-control" />
                <span asp-validation-for="GroupTirePrice.StartDate" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="GroupTirePrice.Type" class="control-label"></label>
                <input asp-for="GroupTirePrice.Type" class="form-control" />
                <span asp-validation-for="GroupTirePrice.Type" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="GroupTirePrice.EndDate" class="control-label"></label>
                <input asp-for="GroupTirePrice.EndDate" class="form-control" />
                <span asp-validation-for="GroupTirePrice.EndDate" class="text-danger"></span>
            </div>
            <div class="form-group">
                <div class="checkbox">
                    <label>
                        <input asp-for="GroupTirePrice.IsHidden" /> @Html.DisplayNameFor(model => model.IsHidden))
                    </label>
                </div>
            </div>
            <div class="form-group">
                <label asp-for="GroupTirePrice.GroupId" class="control-label"></label>
                <select asp-for="GroupTirePrice.GroupId" class ="form-control" asp-items="ViewBag.GroupId"></select>
            </div>
            <div class="form-group">
                <label asp-for="GroupTirePrice.TireId" class="control-label"></label>
                <select asp-for="GroupTirePrice.TireId" class ="form-control" asp-items="ViewBag.TireId"></select>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-page="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

ProductManagementSystem/Pages/Price/Delete.cshtml
@page
@model ProductManagementSystem.Pages.Price.DeleteModel

@{
    ViewData["Title"] = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>GroupTirePrice</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.GroupTirePrice.Price)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.GroupTirePrice.Price)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.GroupTirePrice.StartDate)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.GroupTirePrice.StartDate)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.GroupTirePrice.EndDate)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.GroupTirePrice.EndDate)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.GroupTirePrice.IsHidden)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.GroupTirePrice.IsHidden)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.GroupTirePrice.Group)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.GroupTirePrice.Group.Name)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.GroupTirePrice.Tire)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.GroupTirePrice.Tire.Discriminator)
        </dd>
    </dl>
    
    <form method="post">
        <input type="hidden" asp-for="GroupTirePrice.Type" />
        <input type="hidden" asp-for="GroupTirePrice.GroupId" />
        <input type="hidden" asp-for="GroupTirePrice.TireId" />
        <input type="submit" value="Delete" class="btn btn-default" /> |
        <a asp-page="./Index">Back to List</a>
    </form>
</div>

ProductManagementSystem/Pages/Price/Details.cshtml
@page
@model ProductManagementSystem.Pages.Price.DetailsModel

@{
    ViewData["Title"] = "Details";
}

<h2>Details</h2>

<div>
    <h4>GroupTirePrice</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.GroupTirePrice.Price)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.GroupTirePrice.Price)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.GroupTirePrice.StartDate)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.GroupTirePrice.StartDate)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.GroupTirePrice.EndDate)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.GroupTirePrice.EndDate)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.GroupTirePrice.IsHidden)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.GroupTirePrice.IsHidden)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.GroupTirePrice.Group)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.GroupTirePrice.Group.Name)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.GroupTirePrice.Tire)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.GroupTirePrice.Tire.Discriminator)
        </dd>
    </dl>
</div>
<div>
    @Html.ActionLink("Edit", "Edit", new { /* id = Model.PrimaryKey */ }) |
    <a asp-page="./Index">Back to List</a>
</div>

ProductManagementSystem/Pages/Price/Edit.cshtml
@page
@model ProductManagementSystem.Pages.Price.EditModel

@{
    ViewData["Title"] = "Edit";
}

<h2>Edit</h2>

<h4>GroupTirePrice</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form method="post">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="GroupTirePrice.Price" class="control-label"></label>
                <input asp-for="GroupTirePrice.Price" class="form-control" />
                <span asp-validation-for="GroupTirePrice.Price" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="GroupTirePrice.StartDate" class="control-label"></label>
                <input asp-for="GroupTirePrice.StartDate" class="form-control" />
                <span asp-validation-for="GroupTirePrice.StartDate" class="text-danger"></span>
            </div>
            <input type="hidden" asp-for="GroupTirePrice.Type" />
            <div class="form-group">
                <label asp-for="GroupTirePrice.EndDate" class="control-label"></label>
                <input asp-for="GroupTirePrice.EndDate" class="form-control" />
                <span asp-validation-for="GroupTirePrice.EndDate" class="text-danger"></span>
            </div>
            <div class="form-group">
                <div class="checkbox">
                    <label>
                        <input asp-for="GroupTirePrice.IsHidden" /> @Html.DisplayNameFor(model => model.IsHidden)
                    </label>
                </div>
            </div>
            <input type="hidden" asp-for="GroupTirePrice.GroupId" />
            <input type="hidden" asp-for="GroupTirePrice.TireId" />
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-page="./Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

ProductManagementSystem/Pages/Price/Import.cshtml
@page
@model ProductManagementSystem.Pages.Price.ImportModel
@{
    ViewData["Title"] = "Import";
}

<h2>Import</h2>

<form method="post" enctype="multipart/form-data">
    <div class="input-group">
        <label class="input-group-btn">
            <span class="btn btn-primary">
                Browse… <input style="display: none;" type="file" multiple="" id="fUpload" name="files">
            </span>
        </label>
        <input class="form-control" type="text" readonly="">
    </div>
    <input type="button" id="btnUpload" class="btn btn-primary" value="Upload" />

    @*<button asp-page-handler="Export" class="btn btn-primary">Export</button>*@
    <br />
    <div id="dvData"></div>
</form>

ProductManagementSystem/Pages/Price/Index.cshtml
@page
@model ProductManagementSystem.Pages.Price.IndexModel

@{
    ViewData["Title"] = "Index";
}

<h2>Index</h2>

<p>
    <a asp-page="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
                <th>
                    @Html.DisplayNameFor(model => model.GroupTirePrice[0].Price)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.GroupTirePrice[0].StartDate)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.GroupTirePrice[0].EndDate)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.GroupTirePrice[0].IsHidden)
                </th>
            <th>
                @Html.DisplayNameFor(model => model.GroupTirePrice[0].Group)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.GroupTirePrice[0].Tire)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model.GroupTirePrice) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Price)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.StartDate)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.EndDate)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.IsHidden)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Group.Name)
            </td>
            <td>
                @Html.ActionLink("Edit", "Edit", new { /* id=item.PrimaryKey */ }) |
                @Html.ActionLink("Details", "Details", new { /* id=item.PrimaryKey */ }) |
                @Html.ActionLink("Delete", "Delete", new { /* id=item.PrimaryKey */ })
            </td>
        </tr>
}
    </tbody>
</table>